[tool.poetry]
name = "gtap"
version = "0.1.0"
description = ""
authors = ["Michael Wang <41971562+devmwang@users.noreply.github.com>"]
readme = "README.md"
repository = "https://github.com/devmwang/GTAP"

[tool.poetry.dependencies]
python = "^3.12"
setproctitle = "^1.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
