from __future__ import annotations

from pathlib import Path

DEFAULT_OUTPUT_DIR = Path("blackbox-recordings")
SCHEMA_VERSION = 2
VIDEO_CODEC = "libx264"
VIDEO_CONTAINER = "matroska"
VIDEO_FILE_SUFFIX = ".mkv"
VIDEO_PIXEL_FORMAT = "yuv420p"
VIDEO_PRESET = "veryfast"
VIDEO_CRF = 18
INTEGRITY_EDGE_GRACE_SECONDS = 5.0
INTEGRITY_EDGE_GRACE_NS = int(INTEGRITY_EDGE_GRACE_SECONDS * 1_000_000_000)
INPUT_NOMINAL_HZ = 60.0
INPUT_MAPPING_VERSION = 1
